version: '3.4'

services:
  nextapptest:
    image: nextapptest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./:/nextapptest
      - ./node_modules:/nextapptest/node_modules
      - /nextapptest/.next
